### ISSUE TITLE
MCP Server Plugin Installed but MCP Proxy cannot find anything running

### ISSUE THREAD

**Issue by maxhillaert** [JetBrains/mcp-server-plugin#4]
**test run of mcp proxy**

```
C:\Users\maxhi>set LOG_ENABLED=true

C:\Users\maxhi>npx -y @jetbrains/mcp-proxy
Initializing server...
Server connected to transport.
Attempting to find a working IDE endpoint...
Testing port 63342...
Sending test request to http://localhost:63342/api/mcp/list_tools
Error during testListTools for endpoint http://localhost:63342/api: TypeError: fetch failed
    at node:internal/deps/undici/undici:13484:13
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async testListTools (file:///C:/Users/maxhi/AppData/Local/npm-cache/_npx/216f9f7f9928524d/node_modules/@jetbrains/mcp-proxy/dist/src/index.js:42:21)
    at async findWorkingIDEEndpoint (file:///C:/Users/maxhi/AppData/Local/npm-cache/_npx/216f9f7f9928524d/node_modules/@jetbrains/mcp-proxy/dist/src/index.js:88:27)
    at async updateIDEEndpoint (file:///C:/Users/maxhi/AppData/Local/npm-cache/_npx/216f9f7f9928524d/node_modules/@jetbrains/mcp-proxy/dist/src/index.js:108:26)
    at async runServer (file:///C:/Users/maxhi/AppData/Local/npm-cache/_npx/216f9f7f9928524d/node_modules/@jetbrains/mcp-proxy/dist/src/index.js:231:5) {
  [cause]: Error: connect ECONNREFUSED ::1:63342
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1615:16) {
    errno: -4078,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 63342
  }
}
Port 63342 is not responding correctly.
Testing port 63343...

<<continues all the way to 63352>>

```

There is not indication of what is going on in intellij and what may be the issue.

Here are the log lines I can find in intellij logs

**intellij logs**
```
2024-12-25 13:50:10,677 [ 139817]   INFO - #c.i.i.p.DynamicPlugins - Plugin com.intellij.mcpServer loaded without restart in 125 ms
2024-12-25 13:50:10,677 [ 139817]   INFO - #c.i.i.s.p.i.SharedIndexMainZipStorage - Shared Indexes Storage is opened and empty
2024-12-25 13:50:10,677 [ 139817]   INFO - #o.j.m.MCPServerStartupValidator - Starting npx installation check
2024-12-25 13:50:10,677 [ 139817]   INFO - #o.j.m.MCPServerStartupValidator - Detected Windows OS, using 'where' command
2024-12-25 13:50:10,677 [ 139817]   INFO - #o.j.m.MCPServerStartupValidator - Windows - Environment PATH: null
..
2024-12-25 13:50:10,789 [ 139929]   INFO - #o.j.m.MCPServerStartupValidator - Windows - where npx completed with success: true
2024-12-25 13:50:10,789 [ 139929]   INFO - #o.j.m.MCPServerStartupValidator - Windows - Output: C:\Program Files\nodejs\npx
C:\Program Files\nodejs\npx.cmd
```

**intellij version**
```
IntelliJ IDEA 2024.3.1.1 (Ultimate Edition)
Build #IU-243.22562.218, built on December 18, 2024
Licensed to Max Hillaert
Subscription is active until January 15, 2025.
Runtime version: 21.0.5+8-b631.28 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 11.0
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 20
Registry:
  ide.experimental.ui=true
  i18n.locale=
Non-Bundled Plugins:
  com.intellij.mcpServer (1.0.11)
Kotlin: 243.22562.218-IJ
```

**Comment by MaXal** [comment]
@maxhillaert We published a new version of mcp-proxy 1.5.0 which should fix the connection to the IDE. In your case, we're trying to connect via IPv6 (`::1`) but IDE only accepts IPv4 (`127.0.0.1`).
